// ***************************************************************************
// 
// Test CR Service : AA1F
// 
// ***************************************************************************
// 
// Generated by : CA Plex r7.2.1   (Build 24.003)
// Date - Time  : Friday, December 14, 2018 - 4:09 PM
// Group Model  : O:\OBMOD\Grp\LIPCLASS
// Local Model  : C:\Webclient\LIPCLASS_Local(12142018).mdl
// User         : Admin
// Version      : X12.0
// Level        : V12.0
// Variant      : Base
// Language     : Base
// 
// ***************************************************************************
// 
// Make Processing Support:
/*
@OBJ_SURROGATE=0xFFFFFEF0
@FUNCTION=Test CR Service
@FNCLNGSYS=Java
@IMPLEMENTATION_NAME=AA1F
@TYPE=EXTERNAL
@GENVRL=721
*/


// ***************************************************************************
// External Function: Test CR Service
// ***************************************************************************

package com.lincoln.test;

import ObRun.ObRTTypes.*;
import ObRun.ObFunction.*;
import java.lang.reflect.*;
import java.util.*;
import java.io.*;


// ***************************************************************************
// The variables used by: Test CR Service
// ***************************************************************************

////////////////////////////////////////////////////////////////
// AA1F Variable Group
public final class AA1F_ObOut extends ObVariableGroupX
{
    ////////////////////////////////////////////////////////////////
    // Members

    ////////////////////////////////////////////////////////////////
    // Constructors
    public AA1F_ObOut(ObFunction fnc)
    {
        super(ObVariableGroup.VT_OUTPUT, fnc);
    }

    public AA1F_ObOut(ObApplication obapp)
    {
        super(obapp, ObVariableGroup.VT_OUTPUT);
    }

    public AA1F_ObOut()
    {
        super(ObVariableGroup.VT_OUTPUT, null);
    }





}

// ***************************************************************************
